### ISSUE TITLE
Document how to build your project

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/poa-dapps-keys-generation#2]
1. There is no Doc on howto build your project (`default gulp tasks`, etc)
2. There are some prod, minified files ([`application.js`](https://github.com/oraclesorg/oracles-dapps-keys-generation/blob/master/assets/javascripts/application.js) which should be added to gitignore and removed from repo.

3. Quick suggestion is to use https://github.com/facebookincubator/create-react-app that has everything you need to use in modern web-dev

4. Why does `sweetalert` is not loaded from `package.json` ? Good practice is to NOT include 3rd party libs into the git, and always keep them in package.json

5. Document [`config.json`](https://github.com/oraclesorg/oracles-dapps-keys-generation/blob/master/assets/javascripts/config.json)

**Comment by vbaranov** [comment]
Not relevant
